Remove AXRoleDescription fields
w3c/dpub-aam pull request #14
Opened 2022-10-20 11:00 UTC by mattgarrish

This pull request matches the DPUB AAM with the core by removing the AXRoleDescription fields and replacing them with a note about generating them.

@cookiecrook @avneeshsingh @clapierre @gregoriopellegrino  I know you guys discussed the role announcement issue at TPAC. Could you confirm that this change does not impact those discussions and the possible resolution?

Fixes #11

2022-10-20 13:40 UTC, clapierre commented
Matt I don't see the note about generating the descriptions.  Maybe I missed it?

2022-10-20 13:59 UTC, mattgarrish commented
> Maybe I missed it?

No, looks like it got swapped out with note 2, which doesn't apply to this document, when I did a merge of the main branch to make sure everything was up to date. It's the same note as here: https://w3c.github.io/core-aam/#ftn.note1

I'll get that updated shortly. I just noticed that the core spec also now links to the note. I'll see if I can find the code to do that, too. (I originally started this change last spring and then put it on hold while the other discussions were going on.)

2022-10-20 14:14 UTC, clapierre commented
Looks great now Matt, thanks.

2022-10-20 17:21 UTC, cookiecrook requested changes

2022-10-20 17:21 UTC, cookiecrook commented on index.html
> +								<td>AXRole: <code>AXLink</code><br /> AXSubrole: <code>&lt;nil&gt;</code></td>
We had agreed at TPAC to keep the link subroles, among others. Still investigating a way to add additional clarifiers, but this PR should probably be moved back to Draft until the corresponding ARIA issue is settled.

2022-10-20 17:28 UTC, cookiecrook commented on index.html
> +								<td>AXRole: <code>AXLink</code><br /> AXSubrole: <code>&lt;nil&gt;</code></td>
One of the proposals discussed was to expose the applied aria role through the API... Similar to how the DOM id is exposed.

2022-10-21 00:49 UTC, cookiecrook commented
Current thought is that all existing AX API attributes would be retained, but a few new ones would be added, such as the raw string value of the role attribute, and where needed, some additional bikesheded property that contained the other user-presentable info, "bibliography reference"

2022-10-21 11:37 UTC, mattgarrish commented
> Current thought is that all existing AX API attributes would be retained, but a few new ones would be added

Okay, in that case I'll close off this PR and issue #11.

Do you guys have a sense of how long it will take to find a solution to the announcement issue? We've been sitting on the 1.1 update for a few years now and it has some critical fixes like deprecating the list roles. If it's not a complicated fix, we can keep waiting, but if it's going to take some time to implement a solution would it make sense to move this to a 1.2 release?

2022-10-25 15:47 UTC, closed without merging

2022-10-25 19:21 UTC, cookiecrook commented
Still in discussion with the API owners, but thinking it will likely be with [AXCustomContent](https://developer.apple.com/documentation/accessibility/axcustomcontent).